const QUERY_KEY = {
	GET_MYPAGE_MAIN_DATA: 'GET_MYPAGE_MAIN_DATA',
	GET_MYPAGE_REGISTER_DATA: 'GET_MYPAGE_REGISTER_DATA',
	GET_PRODUCT_DETAIL_DATA: 'GET_PRODUCT_DETAIL_DATA',
}
export default QUERY_KEY
