# repository -> Settings -> Secrets에 아래 나올

# workflow의 이름, 나중에는 해당 값을 사용할 수 있기 떄문에 유니크한 값을 추천
name: gitActionStudy

# workflow를 동작하게하는 trigger
# repo에 push 이벤트가 발생할때마다 실행된다.
# 즉, push말고 다른 이벤트도 존재한다.
on: push

# job은 사용자가 정한 플랫폼을 통해 step이라는 일련의 과정을 실행할 수 있다.
# 여러 개의 job를 사용할 수 있으며, 여러개의 job를 사용할 때는 서로 정보도 교활 할 수있다.
# 그리고 각각 독립적으로도 실행할 수도 있다.
jobs:
  deploy:
    # 해당 job을 리눅스 환경에서 사용한다는것
    runs-on: ubuntu-latest

    #step은 shell script를 실행 할 수도있고,
    # 누군가 만들어 놓은 Action을 사용할 수도 있다.
    steps:
      # 만들어놓은 Action을 사용할 때는 uses라는 키워드를 사용한다.
      - uses: actions/checkout@v3

      # 해당 환경을 Node.js 위에서 실행하겠다는 말입니다.
      # 프로젝트가 리액트이기 떄문입니다.
      # 여기도 누군가 만들어 놓은 Action을 사용하는것입니다.
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

        # with라는 키워드로 Action에 값을 전달할 수 있습니다.
        with:
          node-version: lts/Hydrogen

      # npm install을 실행한다
      - name: Install Dependencies
        run: npm install

      # npm run build를 실행한다
      - name: Build
        run: npm run build
